name: Update CSV

on:
  schedule:
    # Run the workflow every 5 minutes (GitHub's minimum interval)
    - cron: "*/5 * * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # Step 4: Run the Python script
    - name: Run house votes.py
      run: python house votes.py

    # Step 5: Commit and push the updated CSV
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add votes.csv
        git commit -m "Updated votes.csv [skip ci]" || echo "No changes to commit"
        git push
