name: Update CSV Every Minute

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Print working directory and list files
    - name: Debug:Print working directory and list files
      run: |
        pwd
        ls -la

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # Step 5: Run house_votes.py
    - name: Run house_votes.py
      run: python house_votes.py

    # Step 6: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add votes.csv
        git commit -m "Updated votes.csv [skip ci]" || echo "No changes to commit"
        git push
