name: Update CSV Every Minute

on:
  schedule:
    # Run the workflow every minute
    - cron: "*/5 * * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run house_votes.py
      run: python house_votes.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add votes.csv
        git commit -m "Updated votes.csv [skip ci]" || echo "No changes to commit"
        git push
